const car = require("./car")

console.log(car)
console.log(car.getBrand())
console.log(car.getColor())
console.log(car.getPrice())
console.log(car.getID())
console.log(car.getOwner())
console.log(car.setOwner("azole"))
console.log(car.getOwner())